services:
  postgres:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_USER: ${SILVER_DB_USER:-opa}
      POSTGRES_PASSWORD: ${SILVER_DB_PASSWORD:-opa}
      POSTGRES_DB: ${SILVER_DB_NAME:-opa}
    ports:
      - "5432:5432"
    volumes:
      - opa_postgres_data:/var/lib/postgresql/data

volumes:
  opa_postgres_data:
